name: deploy to prod 8600
on:
  push:
    branches: [ openmrs-2.3.3-upgrade ]
jobs:

  build:
    name: Deploy facility reporting module
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        command_timeout: 200m
        script: |
          cd  /apps/github-workflows/kenyaemr-modules
          sudo rm -rf openmrs-module-facilityreporting
          sudo mkdir openmrs-module-facilityreporting
          sudo chown -R cicd2:cicd2 openmrs-module-kenyaemr
          git config --global --add safe.directory /apps/github-workflows/kenyaemr-modules/openmrs-module-facilityreporting      
          cd openmrs-module-facilityreporting
          git clone -b openmrs-2.3.3-upgrade https://github.com/palladiumkenya/openmrs-module-facilityreporting.git .
          git status
          mvn clean install -DskipTests
          sudo rm -rf /var/lib/OpenMRS/modules/facilityreporting-*.omod
          sudo cp /apps/github-workflows/kenyaemr-modules/openmrs-module-facilityreporting/omod/target/facilityreporting-*.omod /var/lib/OpenMRS/modules/
          sudo chown -R tomcat:tomcat /var/lib/OpenMRS/modules/
          sudo chmod +r /var/lib/OpenMRS/modules/*.omod
          sudo chmod 775 /var/lib/OpenMRS/modules/*.omod
          sudo systemctl stop tomcat
          sudo systemctl start tomcat
         
